friend1 = "rakesh";
console.log(friend1);
rakesh = "Hey, how are you?";
console.log(rakesh);
friend2 = "suresh";
console.log(friend2);
suresh = "suresh : I am fine. how are you ";
console.log(suresh);
rakesh = "rakesh : have you find your dream job, or still searching";
console.log(rakesh);
suresh = "suresh : No, but now i have modify my plans like becoming a podcaster" ;
console.log(suresh);
rakesh = "rakesh : thats fantastic bro , wish you all the luck by my side :)" ;
console.log(rakesh);
suresh = "suresh : where can we meet do you use social media !";
console.log(suresh);
rakesh = "rakesh : Yes, you can follow me on linkedin ";
console.log(rakesh);
suresh = "suresh : by which name it is saved ?";
console.log(suresh);
rakesh = "rakesh : I will send you the link through which we can connect. don't worry";
console.log(rakesh);
suresh = "suresh : fine, ok so will have more text game there";
console.log(suresh);
rakesh = "rakesh : right, you can check my achievements and many more accolodes there ";
console.log(rakesh);
suresh ="suresh : ok and you can check my activities too there through post and timelines";
console.log(suresh);
rakesh = "rakesh : ok my mother is calling for dinner so I think we need to stop the conversation , I will meet you someday ";
console.log(rakesh);
suresh ="suresh : ok. I also have to complete my assignment wasn't knowing how time passed so rapidly";
console.log(suresh);
rakesh = "rakesh : when best friends meet time passes quickly ";
console.log(rakesh);
suresh = "suresh : ok bye, goodnight";
console.log(suresh);
rakesh = "rakesh : same 2 you";
console.log(rakesh);